# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"brightness": "01_monadic.ipynb",
         "contrast": "01_monadic.ipynb",
         "equalize": "01_monadic.ipynb",
         "draw_pair": "02_fourier.ipynb",
         "fft_amplitude": "02_fourier.ipynb",
         "gauss1D": "03_convolution.ipynb",
         "conv1D": "03_convolution.ipynb",
         "gaussian_blur": "03_convolution.ipynb",
         "imgload": "utils.ipynb",
         "arr2img": "utils.ipynb",
         "clipvals": "utils.ipynb",
         "plot_hist": "utils.ipynb",
         "plot_cdf": "utils.ipynb"}

modules = ["monadic.py",
           "fourier.py",
           "convolution.py",
           "utils.py"]

doc_url = "https://mskl.github.io/fit-ni-dzo/"

git_url = "https://github.com/mskl/fit-ni-dzo/tree/master/"

def custom_doc_links(name): return None
