# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"imgload": "01_monadic.ipynb",
         "arr2img": "01_monadic.ipynb",
         "clipvals": "01_monadic.ipynb",
         "brightness": "01_monadic.ipynb",
         "contrast": "01_monadic.ipynb",
         "plot_hist": "01_monadic.ipynb",
         "plot_cdf": "01_monadic.ipynb",
         "equalize": "01_monadic.ipynb"}

modules = ["monadic.py"]

doc_url = "https://mskl.github.io/dzotools/"

git_url = "https://github.com/mskl/dzotools/tree/master/"

def custom_doc_links(name): return None
