# AUTOGENERATED! DO NOT EDIT! File to edit: 02_fourier.ipynb (unless otherwise specified).

__all__ = ['arr', 'spectrum']

# Cell
from .utils import imgload, arr2img

arr = imgload(convert="L")
arr2img(arr)

# Cell
import numpy as np

spectrum = np.fft.fft2(np.exp(arr))
arr2img(np.log(1+np.abs(spectrum))*256)