# AUTOGENERATED! DO NOT EDIT! File to edit: 06_image_segmentation.ipynb (unless otherwise specified).

__all__ = ['GREEN', 'RED', 'rescale', 'get_maxflow_graph']

# Cell
import numpy as np
import maxflow

# Cell
GREEN = (0, 255, 0)
RED = (255, 0, 0)

# Cell
rescale = lambda v: 255 * np.exp(-v*v / 64)

# Cell
def get_maxflow_graph(back: np.ndarray, color: np.ndarray) -> (np.ndarray, maxflow.GraphInt):
    """Calculate the segmentation using maxflow graph optimization.

    Assumes that the color array only contains 2 colors where one
    of them is red (255, 0, 0) and the other one green (0, 255, 0).
    """
    graph = maxflow.Graph[int](0, 0)
    nodeids = graph.add_grid_nodes(back.shape)

    graph.add_grid_tedges(
        nodeids,
        np.all(color == RED, axis=-1) * 50,
        np.all(color == GREEN, axis=-1) * 50,
    )

    minx = rescale(255 - np.minimum(back[:, 1:], back[:, :-1]))
    miny = rescale(255 - np.minimum(back[1:, :], back[:-1, :]))

    edgex = np.array(
        [[0, 0, 0],
         [0, 0, 1],
         [0, 0, 0]]
    )
    edgey = np.array(
        [[0, 0, 0],
         [0, 0, 0],
         [0, 1, 0]]
    )

    graph.add_grid_edges(nodeids[:, :-1], minx, edgex, symmetric=True)
    graph.add_grid_edges(nodeids[:-1, :], miny, edgey, symmetric=True)

    return nodeids, graph